---
name: Upstream Sync
'on':
  schedule:
    - cron: "15 6 * * 1"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  synchronise-yoga:
    name: Synchronise yoga
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: yoga
